### ISSUE TITLE
Enhancement / Compatibility

### ISSUE THREAD

**Issue by Rahmiel** [Shnupbups/extra-pieces#13]
This isn't an issue so much as a request/suggestion/information gathering/spitballing thing.

1st: If I am understanding correctly you can config in any block in the instance of MC including modded blocks? The problem is that the syntax in the config is somewhat confusing and cluttered (its a new feature, so its okay).

Edit1: I'm A fool, when I originally read the wiki I assumed it was work in progress and didn't click any links. I find myself a moron, and worship your future-sight in questions like this one.

2nd: If I were to create an entire config for another mod, say Blockus, would it be possible to implement or have "Extra Pieces" detect other mods? Just a future "compatibility" idea.

3rd: In future versions would it be possible to create a config folder instead of one single config allowing a pack maker to create a more organized file structure for adding in the pieces. (I.E. a folder that has vanillablocks.json, blockus.json, othermodhere.json).

Sorry if this is long-winded, just trying to be helpful to what is currently one of the best mod authors supporting Fabric.

**Comment by Shnupbups** [comment]
I'll address your points one by one.

First, I'm aware that the syntax of the config is more than a little bit confusing. I hope to eventually create a tool for easily creating config files with a GUI. I'm glad you found the wiki helpful, but I hope to be more intuitive in future.

Second, the mod will never have pieces for non-vanilla blocks by default. I'm actually considering making the default config blank (or near blank) so that *nothing* has pieces without editing the config, but I'm not sure how that would go down with most users. But as far as official configs for mods, see below...

As for your third point, I do plan to have a config folder that will allow for multiple config JSONs at once in a future version.  I also plan to release official configs to add to the folder for specific mods as 'Piece Packs'. This will include a Blockus pack.

I hope you enjoy the mod! I'm always happy to hear input from users.

**Comment by pansargunnar** [comment]
Hi, I'm having problems with both this mod and Blockus, i got fabric loader and api, all other mods works fine. But with these block mods i can see the mod added to modlist, and i can see the items in inventory, with both Extra Pieces and Blockus, but when i try to place them, they disappear within half a second... Been looking for answers everywere but cant find another person who have the same problem. My friend have the same problem too.

**Comment by Shnupbups** [comment]
A config folder for Piece Packs is implemented as of 2.2.0!
