### ISSUE TITLE
Can't Create a Piece Pack for Grass Blocks

### ISSUE THREAD

**Issue by bellyrose** [Shnupbups/extra-pieces#35]
Tried multiple things, can't seem to make it work at all. I attached a .txt version of the Piece Pack, hope that it's a simple thing I'm just not noticing.

[grass.txt](https://github.com/Shnupbups/extra-pieces/files/3801125/grass.txt)

**Comment by Shnupbups** [comment]
You were missing some commas and a curly bracket. Here's a fixed version. Hope this helps!
Note: the grass will probably look grey because of how Minecraft colours the texture based on biome and that not being set up for the pieces. I may do something to help this in the future.
[grass.txt](https://github.com/Shnupbups/extra-pieces/files/3801261/grass.txt)
