### ISSUE TITLE
update to 1.15

### ISSUE THREAD

**Issue by pjlasl** [Shnupbups/extra-pieces#38]
more of a request than an issue :)

**Comment by Loriborn** [comment]
Current Git build seems to be stable on 15.2, though incompatible with Adorn. You can get around this by using the Git version of Adorn and removing the Extra Pieces compatibility features from the fabric.json of that mod. Otherwise, just download the source and build it.

As far as I am aware though, Extra Pieces doesn't seem to work properly yet with Vanilla Parts at the moment, at least not with the sidings multipart feature.

**Comment by florensie** [comment]
Bump @Shnupbups 
Please put a build up on CF :p

If there's anything holding this back I'm willing to take a look at it.
